### ISSUE TITLE
Server process closes with manager

### ISSUE THREAD

**Issue by Plootie** [Plootie/SIT.Manager.Avalonia#24]
If the manager is set to close after launch the server process closes with it, presumably because it is being registered as a child process

**Comment by Plootie** [comment]
Nevermind yeah, we shut the server down here on application close https://github.com/Plootie/SIT.Manager.Avalonia/blob/d0273fee300a5cc67e4e24af1fa4766d9b2ff734/SIT.Manager.Avalonia/Views/MainWindow.axaml.cs#L21
Trying to brainstorm how to handle this nicely

**Comment by artehe** [comment]
Unless you can think of a better method the one we discussed is the way to go:

- If the user has the option to close launcher after game launch enabled then starting the server should spawn it in a separate window. Just like it would if you launched the server outside of the launcher. Otherwise it should behave the way it does right now.
- We'd probably want to update the start server tooltip to say this and probably.
- Also as an extra add a confirmation dialog when the user tries to close the launcher with the server still running as well.

I think that'd be pretty close to how it currently behaves while resolving this case and avoiding ending up with any processes running which the user needs to use the task manager to resolve
